
export type ClassLevel = '6' | '7' | '8' | '9' | '10' | '11' | '12';

export type Board = 'CBSE' | 'BSEB';

export type Stream = 'Science' | 'Commerce' | 'Arts';

export type Role = 'STUDENT' | 'ADMIN';

export type ContentType = 'NOTES_SIMPLE' | 'NOTES_PREMIUM' | 'MCQ_ANALYSIS' | 'MCQ_SIMPLE' | 'PDF_NOTES';

export interface SubjectProgress {
  currentChapterIndex: number; // Starts at 0 (Chapter 1)
  totalMCQsSolved: number; // Must reach 100 to advance index
}

export interface InboxMessage {
  id: string;
  text: string;
  date: string;
  read: boolean;
}

export interface User {
  id: string; // Login ID
  password: string;
  name: string;
  mobile: string;
  email: string;
  role: Role;
  createdAt: string;
  credits: number; // Premium Credits
  streak: number; // Consecutive days
  lastLoginDate: string; // ISO Date string YYYY-MM-DD
  lastActiveTime?: string; // ISO String for "Online" status
  redeemedCodes: string[]; // List of redeemed code IDs
  
  // Soft Delete / Ban Logic
  isArchived?: boolean; // Acts as Soft Delete / Recycle Bin
  isLocked?: boolean;   // NEW: Hard Lock (Login Denied, but not deleted)
  deletedAt?: string; // ISO Date when deleted. If > 30 days, auto purge.
  recoveryCode?: string; // Generated by Admin to restore account
  
  // GRANULAR BANS
  isChatBanned?: boolean; // Can't send messages
  isGameBanned?: boolean; // Can't play Spin Wheel
  
  // COMMUNICATION
  inbox?: InboxMessage[]; // Messages from Admin
  
  // New Fields for Student Profile
  board?: Board;
  classLevel?: ClassLevel;
  stream?: Stream; // Only for 11/12
  
  // Chat & Premium Features
  isPremium?: boolean;
  lastChatTime?: string; // ISO String for cooldown
  lastSpinTime?: string; // ISO String for Spin Wheel 24h cooldown
  lastRewardClaimDate?: string; // To track daily 3-hour study reward
  
  // Progress Tracking
  progress: Record<string, SubjectProgress>; // Key is subjectID
}

export interface CreditPackage {
  id: string;
  name: string;
  credits: number;
  price: number;
  isPopular?: boolean;
}

export interface PaymentRequest {
  id: string;
  userId: string;
  userName: string;
  packageId: string;
  packageName: string;
  amount: number;
  txnId: string; // User entered Transaction ID/UTR
  status: 'PENDING' | 'APPROVED' | 'REJECTED';
  timestamp: string;
}

// NEW INTERFACE
export interface RecoveryRequest {
  id: string; // User ID
  name: string;
  mobile: string;
  timestamp: string;
  status: 'PENDING' | 'RESOLVED';
}

export interface SystemSettings {
  appName: string;
  themeColor?: string; // NEW: Dynamic Hex Color
  maintenanceMode: boolean;
  customCSS: string; // For dynamic styling updates
  // NEW LOGIC CONTROLS
  apiKeys: string[];      // MULTIPLE API KEYS SUPPORT
  
  // AI CUSTOMIZATION
  noteGenerationPrompt?: string; // Admin can override how AI writes notes

  chatCost: number;       // Default 1
  dailyReward: number;    // Default 3
  signupBonus: number;    // Default 2
  isChatEnabled: boolean; // Global Toggle
  isGameEnabled?: boolean; // NEW: Global Game Toggle
  allowSignup: boolean;   // New: Stop new registrations
  loginMessage: string;   // New: Custom message on Login Screen
  allowedClasses?: ClassLevel[]; // NEW: List of active classes (e.g., ['10', '12']). Missing means all open.
  
  storageCapacity?: string; // NEW: Storage Limit Setting (10GB, 50GB, 100GB)
  
  // MONETIZATION
  isPaymentEnabled?: boolean; // NEW: Master switch for payment
  paymentDisabledMessage?: string; // NEW: Message when locked
  upiId: string;          // Admin UPI ID
  upiName: string;        // Admin Name for Payment
  qrCodeUrl: string;      // Optional QR Image URL
  paymentInstructions: string; // "Pay and send screenshot..."
  packages: CreditPackage[]; // List of packages
}

export interface GiftCode {
  code: string;
  amount: number;
  createdAt: string;
  isRedeemed: boolean;
  redeemedBy?: string; // User ID
  redeemedDate?: string;
  generatedBy: string; // Admin ID (or name)
}

export interface ChatMessage {
  id: string;
  userId: string;
  userName: string;
  userRole: Role;
  text: string;
  timestamp: string;
  isDeleted?: boolean; // Soft delete flag
  deletedAt?: string;  // For 30 day recovery
}

export interface IICPost {
  id: string;
  type: 'TEXT' | 'IMAGE' | 'VIDEO';
  title?: string;
  content: string; // Text content, Base64 Image string, or Video URL
  timestamp: string;
  authorName: string;
}

export interface Subject {
  id: string;
  name: string;
  icon: string;
  color: string;
}

export interface Chapter {
  id: string;
  title: string;
  description?: string;
}

export interface MCQItem {
  question: string;
  options: string[];
  correctAnswer: number; // Index 0-3
  explanation: string;
}

export interface LessonContent {
  id: string; // unique ID for history
  title: string;
  subtitle: string;
  content: string; // Markdown or JSON string for MCQ or Base64/URL for PDF
  type: ContentType;
  dateCreated: string;
  subjectName: string;
  mcqData?: MCQItem[]; // Structure for MCQ mode
}

export type ViewState = 'BOARDS' | 'CLASSES' | 'STREAMS' | 'SUBJECTS' | 'CHAPTERS' | 'LESSON' | 'ADMIN_DASHBOARD' | 'AUDIO_STUDIO' | 'STUDENT_DASHBOARD' | 'UNIVERSAL_CHAT' | 'RULES' | 'IIC';

export type StudentTab = 'ROUTINE' | 'CHAT' | 'HISTORY' | 'REDEEM' | 'PREMIUM' | 'GAME';

export type Language = 'English' | 'Hindi';

export interface AppState {
  user: User | null;
  originalAdmin: User | null; // NEW: Track Admin when viewing as user
  view: ViewState;
  selectedBoard: Board | null;
  selectedClass: ClassLevel | null;
  selectedStream: Stream | null;
  selectedSubject: Subject | null;
  selectedChapter: Chapter | null;
  chapters: Chapter[];
  lessonContent: LessonContent | null;
  loading: boolean;
  error: string | null;
  language: Language;
  showWelcome: boolean; // Control welcome popup
  globalMessage: string | null; // Admin Broadcast
  settings: SystemSettings; // New Global Settings
}
